# ===SCENE===
GRSCENE_BACKGROUND_COLOR = "#393939"
GRSCENE_WIDTH = 64000
GRSCENE_HEIGHT = 64000
GRSCENE_GRID_SIZE = 20
GRSCENE_LINE_SPACING = 5
GRSCENE_MAJOR_LINE_COLOR = "292929"
GRSCENE_MINOR_LINE_COLOR = "2f2f2f"
GRSCENE_MAJOR_LINE_PEN_WIDTH = 2
GRSCENE_MINOR_LINE_PEN_WIDTH = 1
GRSCENE_GRID_LINES = False

# ===VIEW===
# * Qt.ScrollBarPolicy 1 OFF 2 ONE
GRVIEW_VERT_SCROLLBAR = 1
GRVIEW_HORZ_SCROLLBAR = 1
GRVIEW_ZOOM_IN_FACTOR = 1.25
GRVIEW_ZOOM_CLAMPED = False
GRVIEW_ZOOM = 10
GRVIEW_ZOOM_STEP = 1
GRVIEW_ZOOM_RANGE_MIN = 0
GRVIEW_ZOOM_RANGE_MAX = 10
GRVIEW_OP_MODE_DEFAULT = 0
GRVIEW_OP_MODE_PAN_VIEW = 1
GRVIEW_OP_MODE_SELECTION = 2
GRVIEW_OP_MODE_EDGE_DRAG = 3


# ===NODE===
# https://www.w3schools.com/colors/colors_picker.asp
GRNODE_TITLE_COLOR = "#ffffff"
GRNODE_TITLE_FONT = "Ubuntu"
GRNODE_TITLE_FONT_SIZE = 10
GRNODE_TITLE_HEIGHT = 24.0
GRNODE_TITLE_PADDING = 4
GRNODE_NODE_WIDHT = 240
GRNODE_NODE_HEIGHT = 180
GRNODE_EDGE_SIZE = 5
GRNODE_COLOR_DEFAULT = "#000000"
GRNODE_COLOR_SELECTED = "#00ff00"
GRNODE_COLOR_TITLE = "#FF313131"
GRNODE_COLOR_BACKGROUND = "#E3232323"

# ===SOCKET===
GRSOCKET_TYPE_INPUT = 1
GRSOCKET_TYPE_OUTPUT = 2
GRSOCKET_RADIUS = 8.0
GRSOCKET_WIDTH_OUTLINE = 2.0
GRSOCKET_COLOR_OUTLINE = "#FF000000"
GRSOCKET_COLOR_BACKGROUND = "#FFFF7700"
GRSOCKET_COLOR_HOVER = "#00ff80"
GRSOCKET_POS_LEFT_TOP = 1
GRSOCKET_POS_LEFT_BOTTOM = 2
GRSOCKET_POS_RIGHT_TOP = 3
GRSOCKET_POS_RIGHT_BOTTOM = 4
GRSOCKET_SPACING = 25


# ===EDGE===
GREDGE_COLOR_DEFAULT = "#001000"
GREDGE_COLOR_SELECTED = "#00FF00"
GREDGE_WIDTH = 3
GREDGE_PATH_DIRECT = 1
GREDGE_PATH_SQUARE = 2
GREDGE_PATH_BEZIER = 3
