# ===SCENE===
GRSCENE_BACKGROUND_COLOR = "#393939"
GRSCENE_WIDTH = 64000
GRSCENE_HEIGHT = 64000

GRSCENE_MAJOR_LINE_COLOR = "292929"
GRSCENE_MINOR_LINE_COLOR = "2f2f2f"

GRSCENE_GRID_SIZE = 20
GRSCENE_LINE_SPACING = 5

GRSCENE_MAJOR_LINE_PEN_WIDTH = 2
GRSCENE_MINOR_LINE_PEN_WIDTH = 1

# ===VIEW===
# * Qt.ScrollBarPolicy 1 OFF 2 ONE
GRVIEW_VERT_SCROLLBAR = 1
GRVIEW_HORZ_SCROLLBAR = 1

GRVIEW_ZOOM_IN_FACTOR = 1.25
GRVIEW_ZOOM_CLAMPED = False
GRVIEW_ZOOM = 10
GRVIEW_ZOOM_STEP = 1
GRVIEW_ZOOM_RANGE_MIN = 0
GRVIEW_ZOOM_RANGE_MAX = 10

# ===NODE===
# https://www.w3schools.com/colors/colors_picker.asp
GRNODE_TITLE_COLOR = "#ffffff"
GRNODE_TITLE_FONT = "Ubuntu"
GRNODE_TITLE_FONT_SIZE = 10
GRNODE_TITLE_HEIGHT = 24.0
GRNODE_TITLE_PADDING = 20
GRNODE_NODE_WIDHT = 180
GRNODE_NODE_HEIGHT = 240
GRNODE_EDGE_SIZE = 10.0
GRNODE_COLOR_PEN_DEFAULT = "#000000"
GRNODE_COLOR_PEN_SELECTED = "#00ff00"
GRNODE_COLOR_TITLE = "#FF313131"
GRNODE_COLOR_BACKGROUND = "#E3232323"

# ===SOCKET===
GRSOCKET_RADIUS = 9.0
GRSOCKET_WIDTH_OUTLINE = 3.0
GRSOCKET_COLOR_OUTLINE = "#FF000000"
GRSOCKET_COLOR_BACKGROUND = "#FFFF7700"
